[[keyboard.bindings]]
action = "Paste"
key = "Paste"

[[keyboard.bindings]]
action = "Copy"
key = "Copy"

[[keyboard.bindings]]
action = "ClearLogNotice"
key = "L"
mods = "Control"

[[keyboard.bindings]]
chars = "\f"
key = "L"
mode = "~Vi"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "Home"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "Space"
mode = "Vi"
mods = "Shift|Control"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Space"
mods = "Shift|Control"

[[keyboard.bindings]]
action = "ClearSelection"
key = "Escape"
mode = "Vi"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "I"
mode = "Vi"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "I"
mode = "Vi"

[[keyboard.bindings]]
action = "ScrollLineUp"
key = "Y"
mode = "Vi"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollLineDown"
key = "E"
mode = "Vi"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "G"
mode = "Vi"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "G"
mode = "Vi"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "B"
mode = "Vi"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "F"
mode = "Vi"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollHalfPageUp"
key = "U"
mode = "Vi"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollHalfPageDown"
key = "D"
mode = "Vi"
mods = "Control"

[[keyboard.bindings]]
action = "Copy"
key = "Y"
mode = "Vi"

[[keyboard.bindings]]
action = "ClearSelection"
key = "Y"
mode = "Vi"

[[keyboard.bindings]]
action = "ClearSelection"
key = "Copy"
mode = "Vi"

[[keyboard.bindings]]
action = "ToggleNormalSelection"
key = "V"
mode = "Vi"

[[keyboard.bindings]]
action = "ToggleLineSelection"
key = "V"
mode = "Vi"
mods = "Shift"

[[keyboard.bindings]]
action = "ToggleBlockSelection"
key = "V"
mode = "Vi"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleSemanticSelection"
key = "V"
mode = "Vi"
mods = "Alt"

[[keyboard.bindings]]
action = "Open"
key = "Return"
mode = "Vi"

[[keyboard.bindings]]
action = "Up"
key = "K"
mode = "Vi"

[[keyboard.bindings]]
action = "Down"
key = "J"
mode = "Vi"

[[keyboard.bindings]]
action = "Left"
key = "H"
mode = "Vi"

[[keyboard.bindings]]
action = "Right"
key = "L"
mode = "Vi"

[[keyboard.bindings]]
action = "Up"
key = "Up"
mode = "Vi"

[[keyboard.bindings]]
action = "Down"
key = "Down"
mode = "Vi"

[[keyboard.bindings]]
action = "Left"
key = "Left"
mode = "Vi"

[[keyboard.bindings]]
action = "Right"
key = "Right"
mode = "Vi"

[[keyboard.bindings]]
action = "First"
key = "Key0"
mode = "Vi"

[[keyboard.bindings]]
action = "Last"
key = "Key4"
mode = "Vi"
mods = "Shift"

[[keyboard.bindings]]
action = "FirstOccupied"
key = "Key6"
mode = "Vi"
mods = "Shift"

[[keyboard.bindings]]
action = "High"
key = "H"
mode = "Vi"
mods = "Shift"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "K"
mode = "Vi"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "J"
mode = "Vi"
mods = "Control"

[[colors.indexed_colors]]
color = "0xff9e64"
index = 16

[[colors.indexed_colors]]
color = "0xdb4b4b"
index = 17

[colors.bright]
black = "0x414868"
blue = "0x7aa2f7"
cyan = "0x7dcfff"
green = "0x9ece6a"
magenta = "0xbb9af7"
red = "0xf7768e"
white = "0xc0caf5"
yellow = "0xe0af68"

[colors.normal]
black = "0x15161E"
blue = "0x7aa2f7"
cyan = "0x7dcfff"
green = "0x9ece6a"
magenta = "0xbb9af7"
red = "0xf7768e"
white = "0xa9b1d6"
yellow = "0xe0af68"

[colors.primary]
background = "0x1a1b26"
foreground = "0xc0caf5"

[font]
size = 24

[font.normal]
family = "MesloLGS NF"

[window]
opacity = 1

[keyboard]
